"""Zero-dependency SVG renderers for the shareable "served free" badge + summary card.

Pure string templating (no deps) so a badge can be generated by the CLI
(``freellmpool badge``) and committed to a README, or served live by the proxy at
``/badge.svg`` / ``/summary.svg``. Inputs are plain dicts (a :class:`StatsStore`
snapshot) so rendering stays decoupled from routing.
"""

from __future__ import annotations

from . import savings

_BRAND = "#7c3aed"  # freellmpool purple
_GREEN = "#3fb950"
_INK = "#0d1117"
_PANEL = "#161b22"
_MUTED = "#8b949e"
_TEXT = "#e6edf3"
_FONT = "Verdana,Geneva,DejaVu Sans,sans-serif"


def _esc(s: object) -> str:
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _num(x: object) -> float:
    return float(x) if isinstance(x, (int, float)) else 0.0


def _compact(n: object) -> str:
    v = _num(n)
    for unit, size in (("B", 1e9), ("M", 1e6), ("K", 1e3)):
        if v >= size:
            return f"{v / size:.1f}".rstrip("0").rstrip(".") + unit
    return str(int(v))


def _money(usd: object) -> str:
    v = _num(usd)
    return f"${v:,.2f}" if v >= 1 else f"${v:.4f}"


def _tokens(stats: dict) -> int:
    return int(stats.get("prompt_tokens", 0) or 0) + int(stats.get("completion_tokens", 0) or 0)


def _saved(stats: dict) -> float:
    return savings.usd_saved(stats.get("prompt_tokens"), stats.get("completion_tokens"))


def _twidth(s: str, fs: int) -> int:
    # Rough average glyph advance for the badge font; good enough for layout.
    return int(len(s) * fs * 0.62)


def _flat_badge(label: str, value: str, color: str) -> str:
    """A shields.io-style flat badge (gradient + rounded clip + scale-0.1 text)."""
    fs = 11
    pad = 12
    lw = _twidth(label, fs) + pad
    vw = _twidth(value, fs) + pad
    w = lw + vw
    lcx, vcx = lw * 5, (lw + vw / 2) * 10  # centers, pre-scaled by 10
    ltl, vtl = (lw - pad) * 10, (vw - pad) * 10
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="20" '
        f'role="img" aria-label="{_esc(label)}: {_esc(value)}">'
        f"<title>{_esc(label)}: {_esc(value)}</title>"
        '<linearGradient id="s" x2="0" y2="100%">'
        '<stop offset="0" stop-color="#bbb" stop-opacity=".1"/>'
        '<stop offset="1" stop-opacity=".1"/></linearGradient>'
        f'<clipPath id="r"><rect width="{w}" height="20" rx="3" fill="#fff"/></clipPath>'
        '<g clip-path="url(#r)">'
        f'<rect width="{lw}" height="20" fill="#555"/>'
        f'<rect x="{lw}" width="{vw}" height="20" fill="{color}"/>'
        f'<rect width="{w}" height="20" fill="url(#s)"/></g>'
        f'<g fill="#fff" text-anchor="middle" font-family="{_FONT}" font-size="{fs}">'
        f'<text x="{lcx:.0f}" y="150" fill="#010101" fill-opacity=".3" '
        f'transform="scale(.1)" textLength="{ltl:.0f}">{_esc(label)}</text>'
        f'<text x="{lcx:.0f}" y="140" transform="scale(.1)" '
        f'textLength="{ltl:.0f}">{_esc(label)}</text>'
        f'<text x="{vcx:.0f}" y="150" fill="#010101" fill-opacity=".3" '
        f'transform="scale(.1)" textLength="{vtl:.0f}">{_esc(value)}</text>'
        f'<text x="{vcx:.0f}" y="140" transform="scale(.1)" '
        f'textLength="{vtl:.0f}">{_esc(value)}</text></g></svg>'
    )


def badge_svg(stats: dict, *, label: str = "freellmpool", metric: str = "tokens") -> str:
    """A small embeddable badge. ``metric``: tokens | saved | requests."""
    if metric == "saved":
        value, color = f"{_money(_saved(stats))} saved", _GREEN
    elif metric == "requests":
        value, color = f"{_compact(stats.get('requests', 0))} served", _BRAND
    else:
        value, color = f"{_compact(_tokens(stats))} tokens free", _BRAND
    return _flat_badge(label, value, color)


def summary_svg(stats: dict, leaderboard: list[tuple[str, float]] | None = None) -> str:
    """A larger shareable card: avoided cost, tokens served free, requests, the
    'serving free since' date, and an optional provider leaderboard (name, 0..1)."""
    lb = leaderboard or []
    width, top = 460, 150
    row_h = 22
    height = top + (len(lb) * row_h + 18 if lb else 0)
    since = (stats.get("first_seen") or "")[:10]

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'role="img" aria-label="freellmpool usage summary" font-family="{_FONT}">',
        f'<rect width="{width}" height="{height}" rx="10" fill="{_INK}"/>',
        f'<rect x="1" y="1" width="{width - 2}" height="{height - 2}" rx="9" '
        f'fill="none" stroke="{_PANEL}"/>',
        f'<text x="20" y="34" fill="{_TEXT}" font-size="16" font-weight="bold">freellmpool</text>',
        f'<text x="{width - 20}" y="34" text-anchor="end" fill="{_MUTED}" font-size="12">'
        f"free LLMs, pooled</text>",
        f'<text x="20" y="84" fill="{_GREEN}" font-size="38" font-weight="bold">'
        f"{_esc(_money(_saved(stats)))}</text>",
        f'<text x="20" y="104" fill="{_MUTED}" font-size="12">avoided cost (Claude Opus 4.8 rates)</text>',
        f'<text x="20" y="132" fill="{_TEXT}" font-size="13">'
        f"{_esc(_compact(_tokens(stats)))} tokens served free  ·  "
        f"{_esc(_compact(stats.get('requests', 0)))} requests"
        f"{'  ·  since ' + _esc(since) if since else ''}</text>",
    ]
    if lb:
        bar_x, bar_w = 150, width - 170
        y = top + 4
        parts.append(
            f'<text x="20" y="{y + 10}" fill="{_MUTED}" font-size="11">provider race</text>'
        )
        y += row_h
        top_frac = max((f for _, f in lb), default=1.0) or 1.0
        for name, frac in lb:
            fw = max(2, int(bar_w * min(1.0, max(0.0, frac / top_frac))))
            parts.append(
                f'<text x="20" y="{y + 12}" fill="{_TEXT}" font-size="11">'
                f"{_esc(str(name)[:16])}</text>"
                f'<rect x="{bar_x}" y="{y + 3}" width="{bar_w}" height="12" rx="3" fill="{_PANEL}"/>'
                f'<rect x="{bar_x}" y="{y + 3}" width="{fw}" height="12" rx="3" fill="{_BRAND}"/>'
            )
            y += row_h
    parts.append("</svg>")
    return "".join(parts)
